telegram:
  bot-id: 0
  bot-token: 7237232815:AAH0oXQVH196J0ji85ulH4A2KqVDfG3cZLQ
  bot-username: disposer_bot

app:
  open-weeks-amount: 3
  company:
    name: driving_school

server:
  servlet:
    context-path: /enrollment
#    encoding:
#      charset: UTF-8
#      enabled: true
#      force: true
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/nogotochki
    password: riton
    username: riton
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
  #        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:migrations/changelog.xml
    enabled: true
logging:
  level:
    root: info
    org.hibernate.sql: debug
