text.no_free_slots="??? ????????? ??????"
text.choose_day="???????? ??????? ????"
text.choose_class="???????? ???????"
text.choose_time="???????? ??????? ?????"
text.not_registered="?? ?? ????????????????. ??????????, ??????? \"??????????????????\""
text.choose_assign="??? ??? ??????? ???????????"
text.already_registered="?? ??? ????????????????"
text.write_name="??????? ???? ???:"
text.greeting="??????, %s!"
text.assign="?? ??????? ???????? ? %s %s ? %s ?? %s"
text.enter_phone="??????? ??? ????? ???????? ? ??????? 8XXXXXXXXXX:"
text.enter_wrong_phone="??????????, ??????? ????? ???????? ? ??????? 8XXXXXXXXXX:"
text.registered="???????, ?? ????????????????!"


button.class="?? ???????"
button.register="??????????????????"
button.previous_week="????. ??????"
button.next_week="????. ??????"
button.buy="?????? ?????????/???????"
button.assign="??????????"
button.info="??????????"
button.admin="????? ? ???????????????"