text.no_free_slots=Нет свободных слотов
text.choose_day=Выберите удобный день
text.choose_class=Выберите занятие
text.choose_time=Выберите удобное время
text.not_registered=Вы не зарегистрированы. Пожалуйста, нажмите \"Зарегистрироваться\"
text.choose_assign=Как вам удобнее записаться?
text.already_registered=Вы уже зарегистрированы
text.write_name=Введите ваше имя:
text.greeting=Привет, %s!
text.assign=Вы успешно записаны к %s %s в %s на %s
text.enter_phone=Введите ваш номер телефона в формате 8XXXXXXXXXX:
text.enter_wrong_phone=Пожалуйста, введите номер телефона в формате 8XXXXXXXXXX:
text.registered=Спасибо, вы зарегистрированы!
text.already_assigned=Вы уже записаны на это занятие, либо есть пересечение со временем другой записи


button.class=На занятие
button.register=Зарегистрироваться
button.previous_week=Пред. неделя
button.next_week=След. неделя
button.buy=Купить абонемент/занятие
button.assign=Записаться
button.info=Информация
button.admin=Связь с администратором
